// ==UserScript==
// @name        Dark Mode
// @version     0.1.16
// @author      kkocdko
// @license     Unlicense
// @match       *://*/*
// @exclude-match  *://127.0.0.1:8109/*
// @exclude-match  *://127.0.0.1:9005/*
// @exclude-match  *://127.0.0.1:8080/*
// @exclude-match  *://127.0.0.1:8889/*
// @exclude-match  *://127.0.0.1:9261/*
// @exclude-match  *://127.0.0.1:4000/*
// @exclude-match  *://127.0.0.1:9246/*
// @exclude-match  *://127.0.0.1:9325/*
// @exclude-match  *://127.0.0.1:9304/*
// @exclude-match  *://127.0.0.1:9090/*
// @exclude-match  *://127.0.0.1:9391/*
// @exclude-match  *://127.0.0.1:9538/*
// @exclude-match  *://127.0.0.1:9056/*
// @exclude-match  *://127.0.0.1:9423/*
// @exclude-match  *://192.168.0.247/*
// @exclude-match  *://192.168.0.248/*
// @exclude-match  *://192.168.0.244/*
// @exclude-match  *://47.100.126.230:*/*
// @exclude-match  *://11.22.33.44/*
// @exclude-match  *://127.0.0.1:8090/*
// @exclude-match  *://localhost:8129/*
// @exclude-match  *://127.0.0.1:9453/*
// @exclude-match  *://127.0.0.1:9327/*
// @exclude-match  *://47.114.114.68:13002/*
// @exclude-match  *://172.17.7.*/*
// @exclude-match  *://forum.suse.org.cn/*
// @exclude-match  *://generated.vusercontent.net/*
// @exclude-match  *://caddyserver.com/*
// @exclude-match  *://godbolt.org/*
// @exclude-match  *://v0.dev/*
// @exclude-match  *://*.atlasos.net/*
// @exclude-match  *://ariakit.org/*
// @exclude-match  *://xanmod.org/*
// @exclude-match  *://without.boats/*
// @exclude-match  *://mirrors.tuna.tsinghua.edu.cn/*
// @exclude-match  *://discord.com/*
// @exclude-match  *://ark-ui.com/*
// @exclude-match  *://sekai.icu/*
// @exclude-match  *://xdaforums.com/*
// @exclude-match  *://replit.com/*
// @exclude-match  *://*.moment.co/*
// @exclude-match  *://predr.ag/*
// @exclude-match  *://man.openbsd.org/*
// @exclude-match  *://vscode.dev/*
// @exclude-match  *://*.nextweb.fun/*
// @exclude-match  *://ianlecorbeau.github.io/blog/*
// @exclude-match  *://netplan.readthedocs.io/*
// @exclude-match  *://124.222.123.153:9304/*
// @exclude-match  *://html5.gamedistribution.com/*
// @exclude-match  *://skydom.pecpoc.com/*
// @exclude-match  *://*.codeium.com/*
// @exclude-match  *://*.babylonjs.com/*
// @exclude-match  *://online-go.com/*
// @exclude-match  *://*.web.dev/*
// @exclude-match  *://twitter.com/*
// @exclude-match  *://rust-lang.github.io/*
// @exclude-match  *://*.go.dev/*
// @exclude-match  *://oledera.samsungdisplay.com/*
// @exclude-match  *://obsproject.com/*
// @exclude-match  *://*.xda-developers.com/*
// @exclude-match  *://mirrorz.org/*
// @exclude-match  *://codesandbox.io/*
// @exclude-match  *://live.bilibili.com/*
// @exclude-match  *://*.lhr.life/*
// @exclude-match  *://caniuse.com/*
// @exclude-match  *://*.reddit.com/*
// @exclude-match  *://*.cdnjs.com/*
// @exclude-match  *://slint-ui.com/*
// @exclude-match  *://ffmpeg.org/*
// @exclude-match  *://nas.iot4im.com:13001/*
// @exclude-match  *://docs.python.org/*
// @exclude-match  *://nas.iot4im.com:14001/*
// @exclude-match  *://*.y8.com/*
// @exclude-match  *://mirror.nju.edu.cn/*
// @exclude-match  *://nnethercote.github.io/perf-book/*
// @exclude-match  *://colab.research.google.com/*
// @exclude-match  *://danielyxie.github.io/bitburner/*
// @exclude-match  *://turtle.codemao.cn/*
// @exclude-match  *://8.219.185.10:9304/*
// @exclude-match  *://bun.sh/*
// @exclude-match  *://regex101.com/*
// @exclude-match  *://react.fluentui.dev/*
// @exclude-match  *://raw.githubusercontent.com/*
// @exclude-match  *://codepen.io/*
// @exclude-match  *://chakra-ui.com/*
// @exclude-match  *://rcore-os.cn/*
// @exclude-match  *://*.cloud.tencent.com/*
// @exclude-match  *://www.theseus-os.com/Theseus/book/*
// @exclude-match  *://blog.csdn.net/zSY_snake/article/details/*
// @exclude-match  *://ui.shadcn.com/*
// @exclude-match  *://*.radix-ui.com/*
// @exclude-match  *://*.js13kgames.com/*
// @exclude-match  *://esp-rs.github.io/*
// @exclude-match  *://*.openai.com/*
// @exclude-match  *://*.toolpad.io/*
// @exclude-match  *://*.tailwindcss.com/*
// @exclude-match  *://*.tailwindui.com/*
// @exclude-match  *://*.mui.com/*
// @exclude-match  *://*.github.com/*
// @exclude-match  *://*.github.dev/*
// @exclude-match  *://download-directory.github.io/*
// @exclude-match  *://web.telegram.org/*
// @exclude-match  *://developer.mozilla.org/*
// @exclude-match  *://www.google.com/*
// @exclude-match  *://*.youtube.com/*
// @exclude-match  *://esbuild.github.io/*
// @exclude-match  *://flutter.github.io/*
// @exclude-match  *://gallery.flutter.dev/*
// @exclude-match  *://happy0316.top/*
// @exclude-match  *://*.bilibili.com/*
// @exclude-match  *://parceljs.org/*
// @exclude-match  *://instant.1point3acres.com/*
// @exclude-match  *://www.webrtc-experiment.com/*
// @exclude-match  *://live.mdnplay.dev/*
// @exclude-match  *://*.mdn.mozilla.net/*
// @exclude-match  *://cdn.jsdelivr.net/*
// @exclude-match  *://nb.nextweb.fun/*
// @exclude-match  *://doc.rust-lang.org/*
// @exclude-match  *://kkocdko.site/toy/*
// @exclude-match  *://ecs-workbench.aliyun.com/*
// @exclude-match  *://shapezio.fandom.com/*
// @exclude-match  *://www.bilibili.com/robots.txt
// @run-at      document-start
// @inject-into content
// ==/UserScript==

document.documentElement.style.background = "#000";
document.documentElement.style.backgroundColor = "#000";
document.head.appendChild(document.createElement("style")).textContent = `
html,body,header,footer{background:#fff!important;background-color:#fff!important;}
html{filter:invert(1) hue-rotate(180deg) brightness(1.2)!important;}
body>pre:first-child:last-child{color:#000!important;color-scheme:light!important;}
`;
// *{background-color:#fff!important;}
